### ISSUE TITLE
Provide helpful commands to virtual server user

### ISSUE THREAD

**Issue by ivilata** [eReuse/workbench#45]
Some commands may be printed on login of the `ereuse` user, e.g. how to edit `config.ini`. This should be extra useful since the server may not have a connection to the Internet.

**Comment by ivilata** [comment]
The image I'm preparing shows, after login, a list of useful commands.  Also, the commands are "preloaded" in history.

![virtualbox_ereusepxeserver-7](https://cloud.githubusercontent.com/assets/420791/20623158/932953bc-b306-11e6-9ffa-8fb058f9a989.png)

**Comment by ivilata** [comment]
Assigning to @bustawin for review.

**Comment by bustawin** [comment]
Done.
