### ISSUE TITLE
Change the name of the project

### ISSUE THREAD

**Issue by bustawin** [eReuse/workbench#48]
The project should update in code and in github the new name: Device Diagnostic and Inventory

**Comment by ivilata** [comment]
Commit ad0c8906 of branch ``rename-ddi-48`` has scripts renamed to ``ddi-*`` and appearances of the project name changed into "Device Diagnostic and Inventory (DDI)".

The package name and GitHub URL are kept the same.

**Comment by ivilata** [comment]
Commit f306f700 of branch ``rename-ddi-48`` has the package name changed to ``ereuse_ddi`` and the ``device-inventory`` script renamed to ``ddi``. I've tested it and it works.

The GitHub URL is still the same.

**Comment by ivilata** [comment]
Just completed the renaming. @bustawin, one thing missing is renaming <http://www.ereuse.org/en/device-diagnostic/> (plus links and related pages) to <http://www.ereuse.org/en/workbench/> in the web pages. Thanks!
