### ISSUE TITLE
Avoid duplicate JSON

### ISSUE THREAD

**Issue by bustawin** [eReuse/workbench#57]
There should be a way to add a fingerprint to a JSON, so DeviceHub can know if it was uploaded before and it is a duplicate.

For example, the fingerprint could be achieved if DeviceInventory adds a date to the computer (even if the date is wrong).

**Comment by ivilata** [comment]
I guess that adding a UUID is the way to go and avoid reinventing the wheel.

**Comment by ivilata** [comment]
Reopening this and assigning since the solution is lacking the server side.

The previous commit adds a random UUID as the string field ``_uuid``. Assigning to @bustawin for validation and server side.

**Comment by bustawin** [comment]
Just make a pre-release and next week I will change it to full-release once I do it server-side.

**Comment by ivilata** [comment]
Watch out for 8.0a1 in a few minutes!
