### ISSUE TITLE
"instalar" script: home partition support

### ISSUE THREAD

**Issue by txapelgorri** [eReuse/workbench#81]
The Reciclanet version of "instalar" script does have support for 3 partitions / mount points: root, swap and home. It would be great to finish this capability too in eReuse's fork.

Some considerations:
* There is a variable (HD_ROOT) here that you can use to say that you need 2 or 3 partitions (values 'FILL' or 'amount' un MiBs): https://github.com/eReuse/SCRIPTS/blob/e552dea6f302cd81b542d5fecaba0d22c1aa4bc0/instalar#L18
* When the scripts tries to set the home partition depending on the value of HD_ROOT, right now it does not dump home.fsa image, but the same image for root partition: https://github.com/eReuse/SCRIPTS/blob/e552dea6f302cd81b542d5fecaba0d22c1aa4bc0/instalar#L162

Our proposal is to create manually 2 FSA files: my_image_root.fsa and my_image_home.fsa, and set instalar to try to restore them if HD_ROOT is other than 'FILL'. The main point here would be to agree a standard way to name those files (_root.fsa and _home.fsa).

Also to set HD_ROOT from eReuse's config.ini file we suggest 2 more changes:

* Add HD_ROOT to config.ini: this way 2/3 partitions availability can be customizable.
* Change the Workbench to read the value from config.ini, maybe here?: https://github.com/eReuse/workbench/blob/05cdbf88d6c3d90e6654fc54fe687a40da4cb499/ereuse_workbench/workbench.py#L213 (right now seems to be hardcoded).

**Comment by bustawin** [comment]
Interesting. Let us continue discussion in [taiga](https://tree.taiga.io/project/ereuseorg-workbench/issue/49)

**Comment by txapelgorri** [comment]
We have workarounded the issue by now modifying donator.py slightly, and also config.ini (we are talking about 8.01beta release): we understand that this issue is probably outdated as we see lots of changes out there :) Soooo, I'm closing it ;)

**Comment by txapelgorri** [comment]
We have workarounded the issue by now modifying donator.py slightly, and also config.ini (we are talking about 8.01beta release): we understand that this issue is probably outdated as we see lots of changes out there :) Soooo, I'm closing it ;)

**Comment by reciclanet** [comment]
Fantastic Ibon, it works very well right now.

**Comment by txapelgorri** [comment]
Copy that! ;)
